import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// মেয়াদ শেষের তারিখ
const EXPIRY_DATE = new Date("2025-02-16T16:40:00Z");

// মেয়াদ শেষ হয়েছে কিনা চেক করা ফাংশন
const isExpired = () => new Date() > EXPIRY_DATE;

// **SEO ফ্রেন্ডলি Metadata ফাংশন**
export async function generateMetadata(): Promise<Metadata> {
  const expired = isExpired();
  return {
    title: expired ? "Hosting Expired - Contact Developer" : "Create Next App",
    description: expired
      ? "Hosting has expired. Please contact the developer."
      : "Generated by create next app",
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const expired = isExpired();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!expired ? (
          <>
            <Navbar />
            {children}
          </>
        ) : (
          <div className="flex flex-col items-center justify-center min-h-screen bg-red-100 text-red-600 text-center p-6">
            <h1 className="text-3xl font-bold">⚠ হোস্টিং এর মেয়াদ শেষ হয়ে গেছে</h1>
            <p className="mt-2 text-lg">দয়া করে ডেভেলপারের সাথে যোগাযোগ করুন।</p>
            <div className="mt-4 p-4 bg-white rounded shadow">
              <p className="text-lg font-semibold">ডেভেলপার তথ্য:</p>
              <p>👤 নাম: SWD Rana</p>
              <p>📧 ইমেইল: codingbengal@gmail.com</p>
              <p>
                🌐 ওয়েবসাইট:{" "}
                <a href="https://swdrana.com" className="text-blue-500 underline" target="_blank">
                  swdrana.com
                </a>
              </p>
              <p>
                🌐 ফেসবুক:{" "}
                <a href="https://facebook.com/swdrana" className="text-blue-500 underline" target="_blank">
                  facebook.com/swdrana
                </a>
              </p>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
