export default function Home() {
  return (
    <main className="container mx-auto">
      {/* rafi-international-trade-and-technology */}
      <h1 className=" text-2xl text-center p-28 sticky top-0 bg-base-100">Welcome to Rafi International Trade and technology</h1>
      <p className=" text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel teneturLorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel teneturLorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel teneturLorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel teneturLorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur.</p>

      <p className=" text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur.</p>

      <p className=" text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur.</p>
      <p className=" text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum, est! Iusto velit facere exercitationem illo est voluptatibus ipsam officia ipsum eligendi necessitatibus! Expedita incidunt perspiciatis aperiam at neque vel tenetur.</p>
    </main>
  );
}
