# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    # self-hosted ই লিখতে হবে এখানে
    runs-on: self-hosted

    strategy:
      matrix:
      # VPS এর Node Version দিতে হবে (Array এর মধ্যে কমা দিয়ে multiple ভার্শন দেওয়া যাবে) 
        node-version: [22.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
    # এটা আসবে Seeting   ->   Secrets and Variables  -> Actions -> Repository Secrets
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    # নিচের লাইন টি বন্ধ করতে হবে কারণ এটা testing করার জন্য
    # - run: npm test
